# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(blank=True, max_length=100, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], default='PR', max_length=2)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mahasiswa',
                'ordering': ['id'],
            },
        ),
    ]
