# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jaringan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.IntegerField(default=0)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jaringans', to='orm.Mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.IntegerField(default=0)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='orm.Mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Rpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.IntegerField(default=0)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rpls', to='orm.Mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Tesdasar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai', models.IntegerField(default=0)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tesdasars', to='orm.Mahasiswa')),
            ],
        ),
    ]
