# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_jaringan_multimedia_rpl_tesdasar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jaringan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='multimedia',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rpl',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tesdasar',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='jaringan',
            table='jaringan',
        ),
        migrations.AlterModelTable(
            name='multimedia',
            table='multimedia',
        ),
        migrations.AlterModelTable(
            name='rpl',
            table='rpl',
        ),
        migrations.AlterModelTable(
            name='tesdasar',
            table='tesdasar',
        ),
    ]
