# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20181122_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jaringan',
            name='grade',
        ),
        migrations.AddField(
            model_name='jaringan',
            name='Grade',
            field=models.CharField(choices=[(('6',), 'A+'), (('5',), 'A'), (('4',), 'B+'), (('3',), 'B'), (('2',), 'C'), (('1',), 'D')], default='...', max_length=1),
        ),
    ]
