# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20181122_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesdasar',
            name='nilai',
        ),
        migrations.AddField(
            model_name='tesdasar',
            name='Grade_Jaringan',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2),
        ),
        migrations.AddField(
            model_name='tesdasar',
            name='Grade_Multimedia',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2),
        ),
        migrations.AddField(
            model_name='tesdasar',
            name='Grade_RPL',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2),
        ),
    ]
