# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20181122_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesdasar',
            name='Grade_Jaringan',
        ),
        migrations.RemoveField(
            model_name='tesdasar',
            name='Grade_Multimedia',
        ),
        migrations.RemoveField(
            model_name='tesdasar',
            name='Grade_RPL',
        ),
        migrations.AddField(
            model_name='tesdasar',
            name='Nilai_Jaringan',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tesdasar',
            name='Nilai_Multimedia',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tesdasar',
            name='Nilai_RPL',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
