# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_auto_20181122_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesdasar',
            name='Nilai_Jaringan',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tesdasar',
            name='Nilai_Multimedia',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tesdasar',
            name='Nilai_RPL',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
