# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_auto_20181122_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesdasar',
            name='nama',
        ),
    ]
