# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0011_remove_tesdasar_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akademik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Praktikum_Multimedia', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2)),
                ('Teori_Multimedia', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2)),
                ('Praktikum_Jaringan', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2)),
                ('Teori_Jaringan', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2)),
                ('Praktikum_RPL', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2)),
                ('Teori_RPL', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='A+', max_length=2)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akademiks', to='orm.Mahasiswa')),
            ],
            options={
                'db_table': 'akademik',
                'ordering': ['id'],
            },
        ),
    ]
