# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0013_remove_akademik_mahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akademik',
            name='Praktikum_Jaringan',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), (('D',), 'D')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='Praktikum_Multimedia',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), (('D',), 'D')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='Praktikum_RPL',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), (('D',), 'D')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='Teori_Jaringan',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), (('D',), 'D')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='Teori_Multimedia',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), (('D',), 'D')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='Teori_RPL',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), (('D',), 'D')], default='-', max_length=2),
        ),
    ]
