# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0015_auto_20181122_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='akademik',
            name='mahasiswa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='akademiks', to='orm.Mahasiswa'),
        ),
    ]
