# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0017_auto_20181126_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='Praktikum_Multimedia',
            new_name='AutoringTools',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='InteraksiManusiaDanKomputer',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='D', max_length=2),
        ),
    ]
