# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-27 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0018_auto_20181126_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesdasar',
            old_name='Nilai_Jaringan',
            new_name='NilaiJaringan',
        ),
        migrations.RenameField(
            model_name='tesdasar',
            old_name='Nilai_Multimedia',
            new_name='NilaiMultimedia',
        ),
        migrations.RenameField(
            model_name='tesdasar',
            old_name='Nilai_RPL',
            new_name='NilaiRPL',
        ),
    ]
